AWSTemplateFormatVersion: 2010-09-09
Resources:
  ProSubscription:
    Type: Redis::CloudFormation::ProSubscription
    Properties:
      SubscriptionName: !Ref SubscriptionName
      BaseUrl: !Ref BaseUrl
      DryRun: !Ref DryRun
      DeploymentType: !Ref DeploymentType
      PaymentMethod: !Ref PaymentMethod
      PaymentMethodId: !Ref PaymentMethodId
      MemoryStorage: !Ref MemoryStorage
      CloudProviders: !Ref CloudProviders
      RedisVersion: !Ref RedisVersion

Parameters:
  SubscriptionName:
    Type: String
    Description: "[Optional]. Subscription name. Example: My new subscription"
    Default: "Sub187"
  BaseUrl:
    Type: String
    Description: "The Base URL where the API calls are sent."
    Default: "https://api-k8s-cloudapi.qa.redislabs.com"
  DryRun:
    Type: String
    Description: "[Optional]. When 'false': Creates a deployment plan and deploys it (creating any resources required by the plan). When 'true': creates a read-only deployment plan without any resource creation. Example: false. Default: 'false'."
  DeploymentType:
    Type: String
    Description: "[Optional]. Creates a single region subscription. Example: single-region"
  PaymentMethod:
    Type: String
    Description: "[Optional]. Payment method for the requested subscription. If credit card is specified, the payment method Id must be defined. Default: 'credit-card'"
  PaymentMethodId:
    Type: String
    Description: "[Optional]. A valid payment method that was pre-defined in the current account. This value is Optional if 'paymentMethod' is 'marketplace', but Required for all other account types."
    Default: 33292
  MemoryStorage:
    Type: String
    Description: "[Optional]. Optional. Memory storage preference: either 'ram' or a combination of 'ram-and-flash'. Example: ram. Default: 'ram'"
  CloudProviders:
    Type: String
    Description: '[Required as JSON]. Cloud hosting & networking details. Example: [{"regions": [{"region": "us-east-1", "networking": {}}]}]'
    Default: '[{"regions": [{"region": "us-east-1", "networking": {}}]}]'
  RedisVersion:
    Type: String
    Description: "[Optional]. If specified, the redisVersion defines the Redis version of the databases in the subscription. If omitted, the Redis version will be the default (available in 'GET /subscriptions/redis-versions'). Example: 7.2. Default = 'default'"

#Metadata block is used to separate parameters displayed upon stack creation in a more organised order.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
       Label: 
         default: "Subscription Parameters"
       Parameters:
         - BaseUrl
         - SubscriptionName
         - DryRun
         - DeploymentType
         - PaymentMethod
         - PaymentMethodId
         - MemoryStorage
         - CloudProviders
         - RedisVersion
