AWSTemplateFormatVersion: 2010-09-09
Resources:
  SubscriptionPeering:
    Type: Redis::CloudFormation::SubscriptionPeering
    Properties:
      SubscriptionID: !Ref SubscriptionID
      BaseUrl:        !Ref BaseUrl
      Provider:       !Ref Provider
      Region:         !Ref Region
      AwsAccountId:   !Ref AwsAccountId
      VpcId:          !Ref VpcId
      VpcCidr:        !Ref VpcCidr
      VpcCidrs:       !Ref VpcCidrs
      VpcProjectUid:  !Ref VpcProjectUid
      VpcNetworkName: !Ref VpcNetworkName

Parameters:
    BaseUrl:
      Type: String
      Description: "[Required]. Base URL link used to connect to API. Example: https://api-k8s-cloudapi.qa.redislabs.com."
    SubscriptionID:
      Type: String
      Description: "[Required]. The ID of the Pro Subscription that will make a peering connection. Example: 163199"
    Provider:
      Type: String
      Description: "[Required]. Cloud provider. Example: AWS. Default AWS"
    Region:
      Type: String
      Description: "[Required]. Deployment region as defined by cloud provider. Example: eu-west-1"
    AwsAccountId:
      Type: String
      Description: "[Required]. AWS Account uid. Example: 178919255282"
    VpcId: 
      Type: String
      Description: "[Required]. VPC uid. Example: vpc-082e1c0b7388260c9"
    VpcCidr:
      Type: String
      Description: "[Optional]. VPC CIDR. Example:  '10.10.10.0/24'"
    VpcCidrs:
      Type: CommaDelimitedList
      Description: "[Optional]. The VPC CIDRs delimited by commas. Example: '10.10.10.0/24,10.10.20.0/24'"
    VpcProjectUid:
      Type: String
      Description: "[Required for GCP]. VPC project uid."
    VpcNetworkName:
      Type: String
      Description: "[Required for GCP]. VPC network name."

#Metadata block is used to separate parameters displayed upon stack creation in a more organised order.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
       Parameters:
         - Provider
         - BaseUrl
         - SubscriptionID
      - 
       Label: 
         default: "AWS Provider Parameters"
       Parameters:
         - Region
         - AwsAccountId
         - VpcId
         - VpcCidr
         - VpcCidrs
      - 
       Label: 
         default: "GCP Provider Parameters"
       Parameters:
         - VpcProjectUid
         - VpcNetworkName