AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a secret in Secrets Manager for Redis Cloud api keys.

Resources:
  RedisCfApiKeysSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties: 
      Name: 'redis/cf_api_keys'
      Description: 'Secret to store API keys for Redis Cloud'
      SecretString: !Sub |
        {
          "x_api_key": "",
          "x_api_secret_key": ""
        }

Outputs:
  SecretARN:
    Description: 'ARN of the Secrets Manager secret'
    Value: !Ref RedisCfApiKeysSecret
    Export:
      Name: RedisCfApiKeysSecretARN
