AWSTemplateFormatVersion: 2010-09-09
Resources:
  ProDatabase:
    Type: Redis::CloudFormation::ProDatabase
    Properties:
      BaseUrl: !Ref BaseUrl
      SubscriptionID: !Ref SubscriptionID
      DryRun: !Ref DryRun
      DatabaseName: !Ref DatabaseName
      Protocol: !Ref Protocol
      Port: !Ref Port
      DatasetSizeInGb: !Ref DatasetSizeInGb
      RespVersion: !Ref RespVersion
      SupportOSSClusterApi: !Ref SupportOSSClusterApi
      UseExternalEndpointForOSSClusterApi: !Ref UseExternalEndpointForOSSClusterApi
      DataPersistence: !Ref DataPersistence
      DataEvictionPolicy: !Ref DataEvictionPolicy
      Replication: !Ref Replication
      Endpoint: !Ref Endpoint
      Encryption: !Ref Encryption
      ServerCert: !Ref ServerCert
      By: !Ref By
      Value: !Ref Value
      LocalThroughputMeasurementRegion: !Ref LocalThroughputMeasurementRegion
      WriteOperationsPerSecond: !Ref WriteOperationsPerSecond
      ReadOperationsPerSecond: !Ref ReadOperationsPerSecond
      AverageItemSizeInBytes: !Ref AverageItemSizeInBytes
      Active: !Ref Active
      Interval: !Ref Interval
      TimeUTC: !Ref TimeUTC
      StorageType: !Ref StorageType
      StoragePath: !Ref StoragePath
      SourceIp: !Ref SourceIp
      PublicCertificatePEMString: !Ref PublicCertificatePEMString
      EnableTls: !Ref EnableTls
      Password: !Ref Password
      SaslUsername: !Ref SaslUsername
      SaslPassword: !Ref SaslPassword
      AlertName: !Ref AlertName
      AlertValue: !Ref AlertValue
      ModuleName: !Ref ModuleName
      ModuleParameters: !Ref ModuleParameters
      QueryPerformanceFactor: !Ref QueryPerformanceFactor
      RegexRules: !Ref RegexRules
      EnableDefaultUser: !Ref EnableDefaultUser

Parameters:
  DatabaseName:
    Type: String
    Description: "[Required]. Database name (Database name must be up to 40 characters long, include only letters, digits, or hyphen ('-'), start with a letter, and end with a letter or digit). Example: Redis-database-example"
    Default: "testdb13"
  BaseUrl:
    Type: String
    Description: "The Base URL where the API calls are sent."
    Default: "https://api-k8s-cloudapi.qa.redislabs.com"
  SubscriptionID:
    Type: String
    Description: "[Required]. The Subscription ID under which the Database is created. Example: 163199"
    Default: "185217"
  DryRun:
    Type: String
    Description: "[Optional]. When 'false': Creates a deployment plan and deploys it (creating any resources required by the plan). When 'true': creates a read-only deployment plan without any resource creation. Example: false. Default: 'false'."
  Protocol:
    Type: String
    Description: "[Optional]. Database protocol: either 'redis' or 'memcached'. Default: 'redis'"
  Port:
    Type: String
    Description: "[Optional]. TCP port on which the database is available (10000-19999). Generated automatically if omitted. Example: 10000"
  DatasetSizeInGb:
    Type: String
    Description: "[Optional]. The maximum amount of data in the dataset for this specific database is in GB. You can not set both datasetSizeInGb and totalMemoryInGb. if 'replication' is true, the database's total memory will be twice as large as the datasetSizeInGb.if 'replication' is false, the database's total memory of the database will be the datasetSizeInGb value. Minimum: 0.1. ExclusiveMinimum: false. Example: 1"
    Default: "1"
  RespVersion:
    Type: String
    Description: "[Optional]. RESP version must be compatible with Redis version. Example: resp3. Allowed values: resp2/resp3."
  SupportOSSClusterApi:
    Type: String
    Description: "[Optional]. Support Redis open-source (OSS) Cluster API. Default: 'false'"
  UseExternalEndpointForOSSClusterApi:
    Type: String
    Description: "[Optional]. Should use external endpoint for open-source (OSS) Cluster API. Can only be enabled if OSS Cluster API support is enabled'. Default: 'false'"
  DataPersistence:
    Type: String
    Description: "[Optional]. Rate of database data persistence (in persistent storage). List of options: [ none, aof-every-1-second, aof-every-write, snapshot-every-1-hour, snapshot-every-6-hours, snapshot-every-12-hours ]. Example: none. Default: 'none'."
  DataEvictionPolicy:
    Type: String
    Description: "[Optional]. Data items eviction method. List of options: [ allkeys-lru, allkeys-lfu, allkeys-random, volatile-lru, volatile-lfu, volatile-random, volatile-ttl, noeviction ]. Default: 'volatile-lru'"
  Replication:
    Type: String
    Description: "[Optional]. Databases replication. Default: 'true'"
  Endpoint:
    Type: String
    Description: "[Required for replica]. A Redis URI (sample format: 'redis://user:password@host:port)'. If the URI provided is Redis Cloud instance, only host and port should be provided (using the format: ['redis://endpoint1:6379', 'redis://endpoint2:6380'] )."
  Encryption:
    Type: String
    Description: "[Optional]. Defines if encryption should be used to connect to the sync source. If left null and if the source is a Redis Cloud instance, it will automatically detect if the source uses encryption."
  ServerCert:
    Type: String
    Description: "[Optional]. TLS/SSL certificate chain of the sync source. If left null and if the source is a Redis Cloud instance, it will automatically detect the certificate to use."
  By:
    Type: String
    Description: "[Required to enable throughputMeasurement]. Throughput measurement method. Either 'number-of-shards' or 'operations-per-second'"
  Value:
    Type: String
    Description: "[Required to enable throughputMeasurement]. Throughput value (as applies to selected measurement method). Example: 10000. Default: 25000 ops/sec"
  LocalThroughputMeasurementRegion:
    Type: String
    Description: "[Optional]. Local throughput for the regional instance of an Active-Active database"
  WriteOperationsPerSecond:
    Type: String
    Description: "[Optional]. Example: 1000. Default: 1000 ops/sec"
  ReadOperationsPerSecond:
    Type: String
    Description: "[Optional]. Example: 1000. Default: 1000 ops/sec"
  AverageItemSizeInBytes:
    Type: String
    Description: "[Optional]. Relevant only to ram-and-flash clusters. Estimated average size (measured in bytes) of the items stored in the database. Default: 1000"
  Active:
    Type: String
    Description: "[Optional]. Determine whether backup should be active or not. Default: null"
  Interval:
    Type: String
    Description: "[Required when active is true]. Represent the interval between backups, should be in the following format every-x-hours where x is one of (24,12,6,4,2,1). for example: 'every-4-hours'."
  TimeUTC:
    Type: String
    Description: "[Optional]. State the hour which the backup will take place. Available only for 12 or 24 hours backup interval. Should be specified an hour for example 2 PM as 14:00"
  StorageType:
    Type: String
    Description: "[Required when active is true]. Type of storage source from which to import the database file (RDB files) or data (Redis connection)"
  StoragePath:
    Type: String
    Description: "[Required when active is true]. Path for backup"
  SourceIp:
    Type: String
    Description: "[Optional]. List of source IP addresses or subnet masks. If specified, Redis clients will be able to connect to this database only from within the specified source IP addresses ranges. example value: '['192.168.10.0/32', '192.168.12.0/24']'"
  PublicCertificatePEMString:
    Type: String
    Description: "[Required for clientTlsCertificates]. Public key certificate (PEM format)"
  EnableTls:
    Type: String
    Description: "[Optional]. When 'true', requires TLS authentication for all connections (mTLS with valid clientSslCertificate, regular TLS when the clientSslCertificate is not provided. Default: 'false'"
  Password:
    Type: String
    Description: "[Optional]. Password to access the database. If omitted, a random 32 character long alphanumeric password will be automatically generated. Can only be set if Database Protocol is REDIS"
  SaslUsername:
    Type: String
    Description: "[Optional]. Memcached (SASL) Username to access the database. If omitted, the username will be set to a 'mc-' prefix followed by a random 5 character long alphanumeric. Can only be set if Database Protocol is MEMCACHED"
  SaslPassword:
    Type: String
    Description: "[Optional]. Memcached (SASL) Password to access the database. If omitted, a random 32 character long alphanumeric password will be automatically generated. Can only be set if Database Protocol is MEMCACHED"
  AlertName:
    Type: String
    Description: "[Required to enable alerts]. Alert name. List of options: [ dataset-size, datasets-size, throughput-higher-than, throughput-lower-than, latency, syncsource-error, syncsource-lag, connections-limit ]. Example: dataset-size"
  AlertValue:
    Type: String
    Description: "[Required to enable alerts]. Alert value. Example: 80"
  ModuleName:
    Type: String
    Description: "[Required only to enable modules]. Redis module Id"
  ModuleParameters:
    Type: String
    Description: "[Optional]. Redis database module parameters (name and value), as relevant to the specific module (see modules parameters specification). Example: OrderedMap {}"
  QueryPerformanceFactor:
    Type: String
    Description: "[Optional]. The query performance factor adds extra compute power specifically for search and query. For databases with search and query, you can increase your search queries per second by the selected factor. Example: 2x"
  RegexRules:
    Type: String
    Description: "[Optional. Can only be modified upon Update request from a Cloud Formation stack]. Shard regex rules. Relevant only for a sharded database."
  EnableDefaultUser:
    Type: String
    Description: "[Optional. Can only be modified upon Update request from a Cloud Formation stack]. When 'true', enables connecting to the database with the 'default' user. Default: 'true'. Can only be set if Database Protocol is REDIS"

#Metadata block is used to separate parameters displayed upon stack creation in a more organised order.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
       Label: 
         default: "Database Parameters"
       Parameters:
         - BaseUrl
         - SubscriptionID
         - DatabaseName
         - DryRun
         - Protocol
         - Port
         - DatasetSizeInGb
         - RespVersion
         - SupportOSSClusterApi
         - UseExternalEndpointForOSSClusterApi
         - DataPersistence
         - DataEvictionPolicy
         - Replication
         - AverageItemSizeInBytes
         - SourceIp
         - EnableTls
         - Password
         - SaslUsername
         - SaslPassword
         - QueryPerformanceFactor
      - 
       Label: 
         default: "replica"
       Parameters:
         - Endpoint
         - Encryption
         - ServerCert
      - 
       Label: 
         default: "throughputMeasurement"
       Parameters:
         - By
         - Value
      -
       Label: 
         default: "localThroughputMeasurement"
       Parameters:
         - LocalThroughputMeasurementRegion
         - WriteOperationsPerSecond
         - ReadOperationsPerSecond
      - 
       Label: 
         default: "remoteBackup"
       Parameters:
         - Active
         - Interval
         - TimeUTC
         - StorageType
         - StoragePath
      - 
       Label: 
         default: "clientTlsCertificates"
       Parameters:
         - PublicCertificatePEMString
      - 
       Label: 
         default: "alerts"
       Parameters:
         - AlertName
         - AlertValue
      - 
       Label: 
         default: "modules"
       Parameters:
         - ModuleName
         - ModuleParameters
      - 
       Label: 
         default: "Parameters supported only for Update action"
       Parameters:
         - RegexRules
         - EnableDefaultUser

