AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${AWS::StackName}-s3bucket"

Outputs:
  BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref MyS3Bucket
